#THIS IS A SAMPLE CONFIG FILE. 
#To run the bot you need to make a copy of this file named "confg.yml" and replace the placeholder values


apitoken: api-token-here

log: 'path/to/log/file'

creator-id: your-id-here
